trigger:
  branches:
    include:
      - main
pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.18.0'
    displayName: 'Usar Node.js 20.18.0'

  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      path: $(npm_cache)
      restoreKeys: |
        npm | "$(Agent.OS)"
    displayName: 'Cache npm dependencies'

  - script: |
      npm install
      npm install react-chartjs-2 chart.js
    displayName: 'Instalar dependencias'

  - script: |
      npm run build --output-path=$(Build.ArtifactStagingDirectory)
    displayName: 'Construir la aplicación'

  - publish: $(Build.ArtifactStagingDirectory)
    artifact: drop
    displayName: 'Publicar artefactos'